{
  "type": "record",
  "name": "identity",
  "namespace": "com.frauddetection.raw",
  "fields": [
    {
      "name": "TransactionID",
      "type": "long"
    },
    {
      "name": "id_01",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_02",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_03",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_04",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_05",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_06",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_07",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_08",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_09",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_10",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_11",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_12",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "id_13",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_14",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_15",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "id_16",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "id_17",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_18",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_19",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_20",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_21",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_22",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_23",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_24",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_25",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_26",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_27",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_28",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "id_29",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "id_30",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "id_31",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "id_32",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "id_33",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "id_34",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "id_35",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "id_36",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "id_37",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "id_38",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "DeviceType",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "DeviceInfo",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}